/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import cordinator.Cordinator;
import domen.Usluga;
import domen.Vlasnik;
import domen.Osoba;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Alexa
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelaUlogovan = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavkeRezervacije = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtbrojUsluga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtukupanIznos = new javax.swing.JTextField();
        btndodajStavku = new javax.swing.JButton();
        btnObrisiStavku = new javax.swing.JButton();
        cmbUsluga = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btnkreirajRezervaciju = new javax.swing.JButton();
        txtIdRezervacija = new javax.swing.JTextField();
        txtDatum = new javax.swing.JTextField();
        cmbOsoba = new javax.swing.JComboBox<>();
        txtKategorija = new javax.swing.JTextField();
        txtPopust = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbVlasnik = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSatOd = new javax.swing.JTextField();
        txtSatDo = new javax.swing.JTextField();
        btnIzmeniRezervaciju = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dobrodošao/la, ");

        tblStavkeRezervacije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavkeRezervacije);

        jLabel2.setText("Stavke rezervacije");

        jLabel3.setText("Usluga ");

        jLabel4.setText("Broj usluga");

        txtbrojUsluga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbrojUslugaActionPerformed(evt);
            }
        });

        jLabel5.setText("Ukupan iznos");

        txtukupanIznos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtukupanIznosActionPerformed(evt);
            }
        });

        btndodajStavku.setText("Dodaj stavku");

        btnObrisiStavku.setText("Obriši stavku");
        btnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStavkuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(btndodajStavku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnObrisiStavku)
                .addGap(215, 215, 215))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbUsluga, 0, 148, Short.MAX_VALUE)
                            .addComponent(txtbrojUsluga)
                            .addComponent(txtukupanIznos)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(383, 383, 383))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbUsluga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtbrojUsluga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtukupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndodajStavku)
                    .addComponent(btnObrisiStavku))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jButton1.setText("Otkaži");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnkreirajRezervaciju.setText("Kreiraj rezervaciju");

        txtIdRezervacija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdRezervacijaActionPerformed(evt);
            }
        });

        jLabel6.setText("Kategorija: ");

        jLabel7.setText("Osoba: ");

        jLabel8.setText("Datum: ");

        jLabel9.setText("Popust: ");

        jLabel10.setText("ID rezervacija");

        jLabel11.setText("Vlasnik: ");

        cmbVlasnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVlasnikActionPerformed(evt);
            }
        });

        jLabel12.setText("Od:");

        jLabel13.setText("Do:");

        btnIzmeniRezervaciju.setText("Izmeni rezervaciju");

        jMenu1.setText("Vlasnik");

        jMenuItem1.setText("Kreiraj vlasnika");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Pretraži vlasnika");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Smena");

        jMenuItem3.setText("Dodaj smenu");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Osoba");

        jMenuItem4.setText("Dodaj osobu");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Pretraži osobu");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Rezervacija");

        jMenuItem6.setText("Pretraži rezervaciju");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnkreirajRezervaciju)
                .addGap(203, 203, 203)
                .addComponent(btnIzmeniRezervaciju)
                .addGap(159, 159, 159)
                .addComponent(jButton1)
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(71, 71, 71)
                                .addComponent(labelaUlogovan, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbVlasnik, 0, 129, Short.MAX_VALUE)
                                    .addComponent(txtIdRezervacija))
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPopust, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(txtSatDo)
                                    .addComponent(txtSatOd))
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDatum)
                                    .addComponent(cmbOsoba, 0, 139, Short.MAX_VALUE)
                                    .addComponent(txtKategorija))))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelaUlogovan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(33, 33, 33)
                                .addComponent(txtSatOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel7)
                            .addComponent(txtSatDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdRezervacija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addComponent(cmbOsoba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(cmbVlasnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtPopust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnkreirajRezervaciju)
                    .addComponent(btnIzmeniRezervaciju))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Cordinator.getInstance().otvoriPrikazVlasnikaFormu();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Cordinator.getInstance().otvoriDodajVlasnikaFormu();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Cordinator.getInstance().otvoriDodajSmenuForma();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            Cordinator.getInstance().otvoriDodajOsobuFormu();
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Cordinator.getInstance().otvoriPrikazOsobeFormu();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void btnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnObrisiStavkuActionPerformed

    private void txtukupanIznosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtukupanIznosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtukupanIznosActionPerformed

    private void txtbrojUslugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbrojUslugaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbrojUslugaActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Cordinator.getInstance().otvoriPrikazRezervacijaForma();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void cmbVlasnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVlasnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbVlasnikActionPerformed

    private void txtIdRezervacijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdRezervacijaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdRezervacijaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    public JLabel getLabelaUlogovan() {
        return labelaUlogovan;
    }

    /**
     * @param args the command line arguments
     */
    public void setLabelaUlogovan(JLabel labelaUlogovan) {
        this.labelaUlogovan = labelaUlogovan;
    }

    public JComboBox<Osoba> getCmbOsoba() {
        return cmbOsoba;
    }

    public void setCmbOsoba(JComboBox<Osoba> cmbOsoba) {
        this.cmbOsoba = cmbOsoba;
    }

    public JComboBox<Usluga> getCmbUsluga() {
        return cmbUsluga;
    }

    public void setCmbUsluga(JComboBox<Usluga> cmbUsluga) {
        this.cmbUsluga = cmbUsluga;
    }

    public JComboBox<Vlasnik> getCmbVlasnik() {
        return cmbVlasnik;
    }

    public void setCmbVlasnik(JComboBox<Vlasnik> cmbVlasnik) {
        this.cmbVlasnik = cmbVlasnik;
    }

    public JTextField getTxtKategorija() {
        return txtKategorija;
    }

    public void setTxtKategorija(JTextField txtKategorija) {
        this.txtKategorija = txtKategorija;
    }

    public JTextField getTxtPopust() {
        return txtPopust;
    }

    public void setTxtPopust(JTextField txtPopust) {
        this.txtPopust = txtPopust;
    }

    public JTable getTblStavkeRezervacije() {
        return tblStavkeRezervacije;
    }

    public void setTblStavkeRezervacije(JTable tblStavkeRezervacije) {
        this.tblStavkeRezervacije = tblStavkeRezervacije;
    }

    public JButton getBtnObrisiStavku() {
        return btnObrisiStavku;
    }

    public void setBtnObrisiStavku(JButton btnObrisiStavku) {
        this.btnObrisiStavku = btnObrisiStavku;
    }

    public JButton getBtndodajStavku() {
        return btndodajStavku;
    }

    public void setBtndodajStavku(JButton btndodajStavku) {
        this.btndodajStavku = btndodajStavku;
    }


    public JButton getBtnkreirajRezervaciju() {
        return btnkreirajRezervaciju;
    }

    public void setBtnkreirajRezervaciju(JButton btnkreirajRezervaciju) {
        this.btnkreirajRezervaciju = btnkreirajRezervaciju;
    }

    public JTextField getTxtDatum() {
        return txtDatum;
    }

    public void setTxtDatum(JTextField txtDatum) {
        this.txtDatum = txtDatum;
    }

    public JTextField getTxtIdRezervacija() {
        return txtIdRezervacija;
    }

    public void setTxtIdRezervacija(JTextField txtIdRezervacija) {
        this.txtIdRezervacija = txtIdRezervacija;
    }

    public JTextField getTxtSatDo() {
        return txtSatDo;
    }

    public void setTxtSatDo(JTextField txtSatDo) {
        this.txtSatDo = txtSatDo;
    }

    public JTextField getTxtSatOd() {
        return txtSatOd;
    }

    public void setTxtSatOd(JTextField txtSatOd) {
        this.txtSatOd = txtSatOd;
    }

    public JTextField getTxtbrojUsluga() {
        return txtbrojUsluga;
    }

    public void setTxtbrojUsluga(JTextField txtbrojUsluga) {
        this.txtbrojUsluga = txtbrojUsluga;
    }

    public JTextField getTxtukupanIznos() {
        return txtukupanIznos;
    }

    public void setTxtukupanIznos(JTextField txtukupanIznos) {
        this.txtukupanIznos = txtukupanIznos;
    }
    
      public void dodajStavkuAddActionListener(ActionListener actionListener){
        btndodajStavku.addActionListener(actionListener);
    
    }
    public void obrisiStavkuAddActionListener(ActionListener actionListener){
        btnObrisiStavku.addActionListener(actionListener);
    
    }
     public void kreirajRezervacijuAddActionListener(ActionListener actionListener){
        btnkreirajRezervaciju.addActionListener(actionListener);
    
    }

    public JButton getBtnIzmeniRezervaciju() {
        return btnIzmeniRezervaciju;
    }

    public void setBtnIzmeniRezervaciju(JButton btnIzmeniRezervaciju) {
        this.btnIzmeniRezervaciju = btnIzmeniRezervaciju;
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniRezervaciju;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JButton btndodajStavku;
    private javax.swing.JButton btnkreirajRezervaciju;
    private javax.swing.JComboBox<Osoba> cmbOsoba;
    private javax.swing.JComboBox<Usluga> cmbUsluga;
    private javax.swing.JComboBox<Vlasnik> cmbVlasnik;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelaUlogovan;
    private javax.swing.JTable tblStavkeRezervacije;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtIdRezervacija;
    private javax.swing.JTextField txtKategorija;
    private javax.swing.JTextField txtPopust;
    private javax.swing.JTextField txtSatDo;
    private javax.swing.JTextField txtSatOd;
    private javax.swing.JTextField txtbrojUsluga;
    private javax.swing.JTextField txtukupanIznos;
    // End of variables declaration//GEN-END:variables

}
